### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by elapt1c** [MCJack123/craftos-pico#1]
`[ 67%] Building ASM object CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj
[ 69%] Building CXX object CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj
cc1plus: warning: '-Werror=' argument '-Werror=implicit-function-declaration' is not valid for C++
[ 70%] Building C object CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj
[ 71%] Building C object CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj
[ 73%] Building C object CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj
[ 74%] Building C object CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/src/rp2_common/pico_multicore/multicore.c.obj
[ 75%] Building C object CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/lib/tinyusb/src/portable/raspberrypi/rp2040/hcd_rp2040.c.obj
[ 76%] Building C object CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/lib/tinyusb/src/portable/raspberrypi/rp2040/rp2040_usb.c.obj
[ 78%] Building C object CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/lib/tinyusb/src/host/usbh.c.obj
[ 79%] Building C object CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/lib/tinyusb/src/host/hub.c.obj
[ 80%] Building C object CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/lib/tinyusb/src/class/cdc/cdc_host.c.obj
[ 82%] Building C object CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/lib/tinyusb/src/class/hid/hid_host.c.obj
[ 83%] Building C object CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/lib/tinyusb/src/class/msc/msc_host.c.obj
[ 84%] Building C object CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/lib/tinyusb/src/class/vendor/vendor_host.c.obj
[ 85%] Building C object CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/lib/tinyusb/src/tusb.c.obj
[ 87%] Building C object CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/lib/tinyusb/src/common/tusb_fifo.c.obj
[ 88%] Building C object CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/lib/tinyusb/hw/bsp/rp2040/family.c.obj
[ 89%] Linking CXX executable craftos.elf
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: CMakeFiles/craftos.dir/home/ubuntu/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj: in function `hold_non_core0_in_bootrom':
(.reset+0x94): undefined reference to `main'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/craftos.dir/build.make:856: craftos.elf] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1788: CMakeFiles/craftos.dir/all] Error 2
gmake: *** [Makefile:103: all] Error 2`

**Comment by MCJack123** [comment]
This project does not work, and is no longer updated.
